export const database = [
  {
    title: "EMOJIS",
    external_link: "",
    id: "001",
    description: "",
    images_url:
      "https://drive.google.com/uc?export=view&id=1r2ff4tfi7SQrIoOTmIo4J2dXhsL8jftU",
    category: "ilustracion",
  },
  {
    title: "JUST A CUTE BEDROOM",
    external_link: "",
    id: "002",
    description: "",
    images_url:
      "https://drive.google.com/uc?export=view&id=1qDrPfFgTBCpkrSp1juT4Dmh8Ggxp_-95",
    category: "3d",
  },
  {
    title: "ZENITSU MINI",
    external_link: "",
    id: "003",
    description: "A MINI ZENITSU WITH GOOD VIBES",
    images_url:
      "https://drive.google.com/uc?export=view&id=1fjxgouc9AvmVe39al4zaZGgPac7QXL2L",
    category: "animacion",
  },
  {
    title: "CRECIENDO EN FAMILIA",
    external_link: "",
    id: "004",
    description: "",
    images_url:
      "https://drive.google.com/uc?export=view&id=1MWZrK2xxkgLqsdgW7LqjY-HXwTSe8_xh",
    category: "ilustracion",
  },
  {
    title: "THE ASTRONAUT",
    external_link: "",
    id: "005",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "DESTACADO",
    external_link: "",
    id: "006",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "HALLOWEEN PARTY",
    external_link: "",
    id: "007",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "TALES FROM THE GAS STATION",
    external_link: "",
    id: "008",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "TELETUBI CONCEPT RACETRACK",
    external_link: "",
    id: "009",
    description: "",
    images_url: "",
    category: "3d",
  },
  {
    title: "MRI CONCEPT EXPERIENCE FOR KIDS",
    external_link: "",
    id: "010",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "BLUEY",
    external_link: "",
    id: "011",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "ISABELLE",
    external_link: "",
    id: "012",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "HOSHINO AI",
    external_link: "",
    id: "013",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "DND",
    external_link: "",
    id: "014",
    description: "",
    images_url: "",
    category: "web",
  },
  {
    title: "MIMOS",
    external_link:
      "https://www.facebook.com/permalink.php?story_fbid=pfbid02gZzBueGta8tUSFcJBEKXtMEnDv7umUeWjtJJMZ4PLnCt9Jn4ebDqKwqYrqeLSpPCl&id=61553251695364",
    id: "01",
    description: "",
    images_url:
      "https://drive.google.com/uc?export=view&id=1V27I4EQmfT33Ylvn5LTZhqDNv8seavYk",
    category: "ilustracion",
  },
];
