export const database = [
  {
    title: "EMOJIS",
    external_link: "",
    id: "001",
    description: "EMOTES",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "JUST A CUTE BEDROOM",
    external_link:
      "https://www.facebook.com/permalink.php?story_fbid=pfbid02gZzBueGta8tUSFcJBEKXtMEnDv7umUeWjtJJMZ4PLnCt9Jn4ebDqKwqYrqeLSpPCl&id=61553251695364",
    id: "002",
    description: "",
    images_url:
      "https://drive.google.com/uc?export=view&id=1h9T1hF51zncrVvB6sdUy_yVNh_jDjwoU",
    category: "3d",
  },
  {
    title: "ZENITSU MINI",
    external_link: "",
    id: "003",
    description: "A MINI ZENITSU WITH GOOD VIBES",
    images_url:
      "https://drive.google.com/uc?export=view&id=1fjxgouc9AvmVe39al4zaZGgPac7QXL2L",
    category: "animacion",
  },
  {
    title: "CRECIENDO EN FAMILIA",
    external_link: "",
    id: "004",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "THE ASTRONAUT",
    external_link: "",
    id: "005",
    description: "A WINDOW WITH A STRANGE GUEST FROM THE SPACE",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "DESTACADO",
    external_link: "",
    id: "006",
    description: "TIPOGRAMAS",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "HALLOWEEN PARTY",
    external_link: "",
    id: "007",
    description: "A GHOST INVITING YOU TO A SPOOKY PARTY",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "TALES FROM THE GAS STATION",
    external_link: "",
    id: "008",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "TELETUBI CONCEPT RACETRACK",
    external_link: "",
    id: "009",
    description: "LOW-POLY RACETRACK",
    images_url: "",
    category: "3d",
  },
  {
    title: "MRI CONCEPT EXPERIENCE FOR KIDS",
    external_link: "",
    id: "010",
    description: "A PROJECT",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "BLUEY",
    external_link: "",
    id: "011",
    description: "BLUEY AND BINGO FROM BLUEY HUMAN VERSION",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "ISABELLE",
    external_link: "",
    id: "012",
    description: "ISABELLE (CANELA) FROM ACNH WITH A HUGE MACHINE GUN",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "HOSHINO AI",
    external_link: "",
    id: "013",
    description: "",
    images_url: "",
    category: "ilustracion",
  },
  {
    title: "DND",
    external_link: "",
    id: "014",
    description: "",
    images_url: "",
    category: "web",
  },
];
